import constantMirror from 'constant-mirror';

export default constantMirror(
  'FETCH_ALL_MATERIALS',
  'FETCH_ALL_SOURCES',
  'FETCH_ALL_PRESETS',
  'POPULATE_QUIZ',
  'CLEAR_QUIZ',
  'UPDATE_MATERIAL',
  'CLEAR_SELECTED_SOURCES',
  'UPDATE_SECTIONS',
  'UPDATE_SOURCES',
  'UPDATE_FORMAT',
  'UPDATE_ADVANCED',
  'CLEAR_ADVANCED',
  'EMIT_ERROR',
  'DISMISS_ERROR',
);
